apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  project: default

  source:
    path: argocd-applications
    repoURL: https://github.com/boonchris/FailFastFeast-argocd.git
    targetRevision: add-kc
  sources: []


  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'  
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 0
operation:
  initiatedBy:
    username: admin
  sync:
    syncStrategy:
      hook: {}
