apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-backend
  template:
    metadata:
      labels:
        app: vote-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-back
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.7
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis