apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-backend
  template:
    metadata:
      labels:
        app: vote-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-back
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: vote-backend
spec:
  selector:
    app: vote-backend
  ports:
  - port: 6379
