apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vote-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: vote-frontend
        image: ghcr.io/boonchris/azure-vote-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "vote-backend"
---
apiVersion: v1
kind: Service
metadata:
  name: vote-frontend
spec:
  selector:
    app: vote-frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: vote.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vote-frontend
                port:
                  number: 80