apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default

  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: keycloak
    targetRevision: 24.4.13
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: keycloak.example
          path: /
  
  destination:    
    server: https://kubernetes.default.svc
    namespace: keycloak

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
